version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "gomod"
    directory: "/bot"
    open-pull-requests-limit: 0
