---
apiVersion: v1
kind: Secret
metadata:
  name: approval-service-files
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  github-app-private-key.pem: {{ .Values.appSecrets.privateKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: approval-service-envvars
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  APPROVAL_SERVICE_WEBHOOK_SECRET: {{ .Values.appSecrets.webhookSecret | b64enc | quote }}
  APPROVAL_SERVICE_INSTALLATION_ID: {{ printf "%.0f" .Values.appSecrets.installationId | b64enc | quote }}
  APPROVAL_SERVICE_APP_ID: {{ printf "%.0f" .Values.appSecrets.appId | b64enc | quote }}
