---
name: Load environment values
description: Load environment values

inputs:
  environments-directory:
    description: Path to the directory containing environments files, defaulting to repo root
  environment-name:
    description: Name of the environment to load
  value-sets:
    description: Name of the value sets to load, separated by new line
  tool-version:
    description: Version of the tool to use

runs:
  using: "composite"
  steps:
    - name: Install env-loader from GitHub Release
      # Relative paths cannot be used here because the action is not guaranteed to be checked out in the same location as the repository using it.
      uses: gravitational/shared-workflows/.github/actions/install-gh-release@41eefbdab5c67d8e0169730e999f73cd315a8cb5
      with:
        tool-name: env-loader
        version: ${{ inputs.tool-version }}
        tag-prefix: tools/env-loader/

    - name: Load environment values into environment variables
      shell: bash
      env:
        ENV_LOADER_ENVIRONMENTS_DIRECTORY: "${{ inputs.environments-directory }}"
        ENV_LOADER_ENVIRONMENT: "${{ inputs.environment-name }}"
        ENV_LOADER_VALUE_SETS: "${{ inputs.value-sets }}"
      run: |
        env-loader --format gha-mask
        env-loader --format gha-env | tee -a "${GITHUB_ENV}"
