name: Amplify Preview
description: Prepare Amplify Preview URL and post it in PR comments
inputs:
  app_ids:
    description: "Comma separated list of Amplify App IDs"
    required: true
  create_branches:
    description: 'Create preview branches using this actions instead of "auto-build" feature on AWS Amplify'
    required: false
    default: "false"
  github_token:
    required: true
    description: "Github token with permissions to read/write comments in pull request"
  wait:
    default: "false"
    description: "If Amplify deployment is pending/running state wait for it's completion"
  wait_retries:
    default: "40"
    description: "Number of attempts to wait before giving up"
  wait_interval:
    default: "30s"
    description: "Interval between checking job status"
runs:
  using: composite
  steps:
    - name: Workaround go cache issue
      # It seems like `setup-go` can't use for cache files outside of ${{ github.workspace }}
      # https://github.com/actions/setup-go/issues/467#issuecomment-2551300160
      shell: bash
      run: |
        # Work around setup-go caching issue
        mkdir -p ${{ github.workspace }}/.tmp/actions/cache/amplify-preview
        go_sum_path=${{ github.workspace }}/.tmp/actions/cache/amplify-preview/go.sum
        cp ${{ github.action_path }}/go.sum ${{ github.workspace }}/.tmp/actions/cache/amplify-preview/
        echo "go_sum_path=${go_sum_path}" >> $GITHUB_OUTPUT
      id: cache_workaround

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - uses: actions/setup-go@v5
      with:
        go-version-file: ${{ github.action_path }}/go.mod
        cache-dependency-path: ${{ steps.cache_workaround.outputs.go_sum_path }}

    - name: Amplify Preview
      env:
        AMPLIFY_APP_IDS: ${{ inputs.app_ids }}
        GIT_BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        CREATE_BRANCHES: ${{ inputs.create_branches }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        WAIT: ${{ inputs.wait }}
        WAIT_RETRIES: ${{ inputs.wait_retries }}
        WAIT_INTERVAL: ${{ inputs.wait_interval }}
      shell: bash
      working-directory: ${{ github.action_path }}
      run: go run .
