---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "approval-service.fullname" . }}
  labels:
    {{- include "approval-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "approval-service.fullname" . }}
  labels:
    {{- include "approval-service.labels" . | nindent 4 }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "approval-service.fullname" . }}
  labels:
    {{- include "approval-service.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "approval-service.fullname" . }}
  apiGroup: "" # Core API
roleRef:
  kind: Role
  name: {{ include "approval-service.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
