name: AMI cleanup tool CD
on:
  push:
    tags:
      - "ami-cleanup-v[0-9]+.[0-9]+.[0-9]+**"

concurrency:
  group: "Only run one instance of AMI cleanup CD for ${{ github.ref_name }}"

jobs:
  cut-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Install Earthly
        uses: earthly/actions-setup@v1.0.8
        with:
          # renovate: earthly-version
          version: v0.7.23
      - name: Determine actual release semver
        env:
          # This is copy/pasted from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
          SEMVER_TAG_REGEX: ^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          GIT_TAG: ${{ github.ref_name }}
        run: |
          # Remove the tool name from the front of the tag
          SEMVER_TAG=$(echo "$GIT_TAG" | sed 's/^ami-cleanup-v//')
          echo "Extracted $SEMVER_TAG from git tag"
          
          # Check if the extracted version is a valid semver
          if ! $(echo "$SEMVER_TAG" | grep --perl-regexp --quiet "$SEMVER_TAG_REGEX"); then
            echo "Extracted version $SEMVER_TAG is not a valid semver" >&2
            exit 1
          fi

          echo "SEMVER_TAG=$SEMVER_TAG" >> $GITHUB_OUTPUT
      - name: Cut a new release for ${{ env.SEMVER_TAG }}
        env:
          GIT_TAG: ${{ github.ref_name }}
        working-directory: tools/ami-cleanup
        run: earthly -ci +release --GIT_TAG="$SEMVER_TAG"
