name: Bloat Check
on:
  workflow_call:
    inputs:
      base_build_dir:
        description: "The base directory of artifacts prior to a change"
        default: ""
        required: true
        type: string
      current_build_dir:
        description: "The current directory of artifacts including the change"
        default: ""
        required: true
        type: string
      artifacts:
        description: "The artifacts in each directory to analyze for bloat"
        default: ""
        required: true
        type: string
jobs:
  bloat:
    name: Bloat Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Run bloat check
        run: go run main.go --artifacts=${{ inputs.artifacts }} --base=${{ inputs.base_build_dir }} --current=${{ inputs.current_build_dir }} > $GITHUB_STEP_SUMMARY
