---
name: Changelog generator CD

on:
  push:
    branches:
      - main
    paths:
      - tools/changelog
    tags:
      - "tools/changelog/v[0-9]+.[0-9]+.[0-9]+**"
  pull_request:
    paths:
      - tools/changelog/workflows/cd.yaml
      - .github/workflows/changelog-cd.yaml
      - .github/workflows/reusable-cd.yaml

jobs:
  release:
    uses: ./.github/workflows/reusable-cd.yaml
    permissions:
      contents: write
      packages: write
    with:
      tool-directory: ./tools/changelog
