on:
  pull_request:
    branches:
      - main
  workflow_call:

name: Lint (GitHub Actions)

jobs:
  check-github-actions:
    name: Check GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for affected paths
        id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            github-actions:
              - '.github/*/**/*.{yaml,yml}'

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@c3a2b64f69b7a1542a68f44d9edbd9ec3fc1455e # v3.0.20
        if: steps.changes.outputs.github-actions == 'true'
        with:
          allowlist: |
            github/
            actions/
            gravitational/shared-workflows/.github/workflows
            gravitational/teleport/.github/workflows
            gravitational/teleport.e/.github/workflows
