name: Lint (JSON)

on:
  workflow_call:

jobs:
  jsonlint:
      name: jsonlint
      runs-on: ubuntu-latest

      permissions:
        contents: read

      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@2d756ea4c53f7f6b397767d8723b3a10a9f35bf2 # v44.0.0
        with:
          files: |
            **/*.json

      - name: jsonlint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            sanitized_file=$(printf '%q' "$file")
            echo "Validating ${sanitized_file}"
            jq empty ${sanitized_file}
          done
