name: Lint (JSON)

on:
  workflow_call:

jobs:
  jsonlint:
    name: jsonlint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          list-files: shell
          filters: |
            json:
              - '**/*.json'

      - name: jsonlint
        if: steps.changed-files.outputs.json == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.json_files }}; do
            sanitized_file=$(printf '%q' "$file")
            echo "Validating ${sanitized_file}"
            jq empty ${sanitized_file}
          done
