name: Lint (JSON)

on:
  workflow_call:

jobs:
  jsonlint:
      name: jsonlint
      runs-on: ubuntu-latest

      permissions:
        contents: read

      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: filter
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        with:
          filters: |
            json:
              - '**/*.json'

      - name: jsonlint
        if: steps.filter.outputs.json == 'true'
        run: |
          for file in ${{ steps.filter.outputs.json_files }}; do
            echo "Validating ${file}"
            jq empty ${file}
          done
