name: Trivy

on:
  workflow_call:

jobs:
  trivy:
      name: trivy
      runs-on: ubuntu-latest

      permissions:
        actions: read
        contents: read
        security-events: write

      steps:
      - name: Disabled
        run: "echo 'Trivy disabled: gravitational/SecOps#358'"
