name: Trivy

on:
  workflow_call:

jobs:
  trivy:
      name: trivy
      runs-on: ubuntu-latest

      permissions:
        actions: read
        contents: read
        security-events: write

      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.11.2
        with:
          scan-type: config
          hide-progress: false
          format: sarif
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true

      - name: Filter SARIF for GitHub
        uses: advanced-security/filter-sarif@v1
        with:
          patterns: |
            -git\\:\\:https\\:/**
          input: 'trivy-results.sarif'
          output: 'trivy-results.filtered.sarif'

      - name: Upload Trivy scan results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.filtered.sarif'
